# NOTE: Planner settings override
misc:
  useCfgCommand: true
  reOptimize: false
  reOptimizeMaxTry: 1000
  enableVis: true
  enableOptVis: false
  optVisRate: 12
  enableBenchmark: true
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/OptBenchmark.csv
  ReachableBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/ReachableBenchmark.csv
  robotProfilePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/RobotProfileRecord.csv

StateSequencePlanner:
  rosRate: 100
  stepTime: 2
  cmdMctsSearchNodeNum: 300
  navMctsSearchNodeNum: 600
  cmdExtrapolatePointNum: 50
  cmdExtrapolateDeltaT: 0.01
  navExtrapolateSamplesNum: 100
  # only for FLTCfgPlanner
  enableReachableFiltering: false
  reachableFilterPoseMoveDis: 0.2
  reachableTravLayerName: "elevation_inpainted_trav"

  # Enable Reachability Check (if envableVis is True, output will be visualized)
  enableReachableCheck: true
  reachableCheckSize: 30 # (size*size, in 0.75*0.75 area)

  swingTrajPreOpt: false
  shutdownAfterPreOpt: false
  execOnKeyboardCmd: false
  # Demo select
  # demoPath: # NOTE: offered by launch file
  savePlannedStates: false
  # Executing saved states on startup
  execSavedStates: false

  # Tripod gait parameters (for hexapod robots)
  useTripodGait: true
  tripodStepDuration: 0.4
  tripodStanceDuration: 0.2

  # Benchmark for StateSequencePlanner
  OptBenchmarkSavePath: /home/user/HexLabCodeSpace/planner_ws/src/analysis_scripts/benchmarking/temp/StateSequencePlannerBenchmark.yaml
