
# NOTE: Planner benchmark settings override 
misc:
  useCfgCommand: true
  reOptimize: false
  reOptimizeMaxTry: 3
  enableVis: false
  enableOptVis: false
  optVisRate: 12
  enableBenchmark: true
  OptBenchmarkSavePath: /home/user/CodeSpace/ROS/planner_ws/src/analysis_scripts/benchmarking/temp/OptBenchmark.csv
  ReachableBenchmarkSavePath: /home/user/CodeSpace/ROS/planner_ws/src/analysis_scripts/benchmarking/temp/ReachableBenchmark.csv
  robotProfilePath: /home/user/CodeSpace/ROS/planner_ws/src/analysis_scripts/benchmarking/temp/RobotProfileRecord.csv

StateSequencePlanner:
  rosRate: 100
  stepTime: 2
  cmdMctsSearchNodeNum: 300
  navMctsSearchNodeNum: 600
  cmdExtrapolatePointNum: 50
  cmdExtrapolateDeltaT: 0.01
  navExtrapolateSamplesNum: 100
  # only for FLTCfgPlanner
  enableReachableFiltering: false
  reachableFilterPoseMoveDis: 0.2
  reachableTravLayerName: "elevation_inpainted_trav"

  # Reachability Check vis
  enableReachableCheck: True
  reachableCheckSize: 30 # (size*size, in 0.75*0.75 area)

  swingTrajPreOpt: true
  shutdownAfterPreOpt: true
  execOnKeyboardCmd: false
  # Demo select
  # demoPath: # NOTE: offered by launch file
  savePlannedStates: false
  # Executing saved states on startup
  execSavedStates: true 

  # Tripod gait parameters (for hexapod robots)
  useTripodGait: false
  tripodStepDuration: 0.4
  tripodStanceDuration: 0.2

  # Benchmark for StateSequencePlanner
  OptBenchmarkSavePath: /home/user/CodeSpace/ROS/planner_ws/src/analysis_scripts/benchmarking/temp/StateSequencePlannerBenchmark.yaml